### ISSUE TITLE
Gets stuck on "Getting current replicas" if redeploying the same commit SHA

### ISSUE THREAD

**Issue by RyanSept** [gigalixir/gigalixir-action#50]
```
Run mhanberg/gigalixir-action@v0.6.2
  with:
    GIGALIXIR_USERNAME: ***
    GIGALIXIR_PASSWORD: ***
    GIGALIXIR_APP: ***
    SSH_PRIVATE_KEY: ***
    GIGALIXIR_CLEAN: false
    MIGRATIONS: true
```

Gets stuck retrying if the given commit SHA had already been deployed
```
Getting current replicas
Waiting 10 seconds...
```
